ALTER TABLE FILMS DROP CONSTRAINT IF EXISTS FILMS_MPA_ID_FK;
ALTER TABLE FRIENDS DROP CONSTRAINT IF EXISTS FRIENDS_USER_ID_FK;
ALTER TABLE FRIENDS DROP CONSTRAINT IF EXISTS FRIENDS_FRIEND_ID_FK;
ALTER TABLE LIKES DROP CONSTRAINT IF EXISTS LIKES_USER_ID_FK;
ALTER TABLE LIKES DROP CONSTRAINT IF EXISTS LIKES_FILM_ID_FK;
ALTER TABLE FILM_GENRES DROP CONSTRAINT IF EXISTS FILM_GENRES_FILM_ID_FK;
ALTER TABLE FILM_GENRES DROP CONSTRAINT IF EXISTS FILM_GENRES_GENRE_ID_FK;

DELETE FROM FRIENDS;
DELETE FROM LIKES;
DELETE FROM FILM_GENRES;
DELETE FROM USERS;
DELETE FROM FILMS;
DELETE FROM GENRES;
DELETE FROM MPA;

DROP TABLE IF EXISTS FRIENDS;
DROP TABLE IF EXISTS LIKES;
DROP TABLE IF EXISTS FILM_GENRES;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS FILMS;
DROP TABLE IF EXISTS GENRES;
DROP TABLE IF EXISTS MPA;